### ISSUE TITLE
v2.0.0-beta13 - Cannot read property 'isLabel' when tab out.

### ISSUE THREAD

**Issue by jeremyhodges** [monterail/vue-multiselect#190]
So far everything appears to be working, but when I tab out of the multiselect I get the following in the console. It doesn't appear if I click out of the multiselect, only on tab out.

```
vue-multiselect.min.js?6cfa:1 Uncaught TypeError: Cannot read property 'isLabel' of undefined
    at VueComponent.addPointerElement (eval at <anonymous> (app.js:803), <anonymous>:1:7053)
    at Proxy.boundFn (eval at <anonymous> (app.js:948), <anonymous>:130:14)
    at Array.eval (eval at <anonymous> (app.js:803), <anonymous>:1:18096)
    at HTMLInputElement.eval (eval at <anonymous> (app.js:948), <anonymous>:2214:22)
```

My component:
```
<multiselect v-model="value"
    :options="options"
    :multiple="true"
    :close-on-select="false"
    :hide-selected="true"
    placeholder="Add Additional Members">
</multiselect>
```

**Comment by shentao** [comment]
Interesting! Thanks for letting me know! Will try to fix this early January.

**Comment by Novynn** [comment]
I found that changing
`this.filteredOptions[this.pointer].isLabel`
to
`this.filteredOptions.length==0||this.filteredOptions[this.pointer].isLabel`
in the minified version fixes this in the meantime.

I guess this is pull request material but the most I can do is post this here.

**Comment by shentao** [comment]
Thanks!

**Comment by shentao** [comment]
Fixed. Should be in the next release.

**Comment by xereda** [comment]
Something similar happens to me if I do not have previously loaded options. If I have the data previously loaded, what happens is the selection of the first option after pressing the "tab" key.

vue@2.1.10
vue-multiselect@2.0.0-beta.13

**Comment by shentao** [comment]
Released. Sorry it’s so late! :(

**Comment by garrettheaver** [comment]
Think this may have introduced a different issue. I was wondering why the "isLabel" error had gone but is replaced by

TypeError: Cannot read property 'id' of null
    at http://localhost:8080/app.js:47334:3556
    at Array.map (native)
    at VueComponent.valueKeys (http://localhost:8080/app.js:47334:3532)

I see valueKeys does a map on internalValue which in turn uses this.value in data(), value also has a watcher which does a deepClone on it. When value=null this is going to cause an issue because we've not got [null] as the value. If I get a chance I'll put together a quick PR

**Comment by mariusa** [comment]
This still happens with 3.1.0 'if I do not have previously loaded options.', as another commenter said
